Importando numpy (e dando um alias "np" a ela)

In [1]:
import numpy as np 

Criando Array simples

In [2]:
np.array([1, 2, 3 ])

array([1, 2, 3])

Array com cinco zeros

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Semelhante a np.zeros(n), mas dessa vez, o array sera preenchido por 1s

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Array com 10 items com valores aleatorios

In [5]:
np.empty(10)

array([6.95332180e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.93101617e-312, 3.80132583e+175, 4.90464331e-062, 7.79078335e-091,
       5.70219451e-066, 8.74029144e-313])

Array com um intervalo especifico

In [6]:
np.arange(4)

array([0, 1, 2, 3])

Definindo um intervalo especifico, dessa vez com mais argumentos

In [7]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

Separa os elemento limearmente, retornando quatro elementos

In [8]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Especifica o tipos de dados forçando certos valores

In [11]:
np.zeros(3, dtype=np.int64)

array([0, 0, 0])

Cria um array  e ordena os elementos

In [12]:
arr = np.array([12, 1, 5, 10, 3, 2, 7])

Ordena um array

In [13]:
np.sort(arr)

array([ 1,  2,  3,  5,  7, 10, 12])

Concatena dois array diferente

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

Essa função trabalha com qualquer dimenção 

In [15]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    ])

Aqui ele irá retornar os valores guardados dentro da váriavel matriz

In [16]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Verifica quantas dimenções a estrutura no objeto

In [17]:
matriz.ndim

2

Verifica quantos atributos tem 

In [19]:
matriz.size

9

Esse atributo retorna qual o formato 

In [20]:
matriz.shape

(3, 3)

Trasforma a matriz mudando o formato da estrutura

In [21]:
matriz.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Pega qualquer matriz convertendo em uma linha ou columa 

In [22]:
a.shape

(3,)

Pega a estrutura e adiciona uma nova dimenção no objeto

In [23]:
a[np.newaxis, :]

array([[1, 2, 3]])

Mostrará o shape da nova estrutura 

In [26]:
a[np.newaxis, :].shape

(1, 3)